spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
    appliction:
      name: springcloud-config-3344-dev
---
spring:
  profiles: test    #测试环境
    appliction:
      name: springcloud-config-3344-test