spring:
  profiles:
    active: dev
---
server: 
  port: 8201
spring:
  profiles: dev #开发环境
  application:
<<<<<<< HEAD
    name: springcloud-study-config-client-dev
=======
    name: springcloud-learn-config-client
>>>>>>> 11d73050aefad759e03d65c35a9ece15ce411d52

eureka:
  client:
    service-url:
      defaultZone: eureka7001.com:7001/eureka
---
server: 
  port: 8202
spring:
  profiles: test #开发环境
  application:
<<<<<<< HEAD
    name: springcloud-study-config-client-test
=======
    name: springcloud-learn-config-client
>>>>>>> 11d73050aefad759e03d65c35a9ece15ce411d52

eureka:
  client:
    service-url:
      defaultZone: eureka7001.com:7001/eureka
#请保存为UTF-8格式
