spring:
  profiles:
    active: dev                                   #当前应用的环境是开发环境
---
server:
  port: 7002

spring:
  profiles: dev
  application:
    name: SPRING-CLOUD-INVENTORY-7002-DEV
  #Spring boot 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_02
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.199.14:7001/eureka/
  instance:
    instance-id: spring-cloud-inventory    #服务实例名称修改
    prefer-ip-address: true   #访问路径显示Ip
#MyBatis配置
#mybatis:
#  type-aliases-package: com.gsau.Inventory.projo
mybatis:
  mapper-locations: classpath:/myBatisConfig/mappers/*.xml
#TxManager配置
tm:
  manager:
    url: http://192.168.199.14:8888/tx/manager/
---
server:
  port: 7002

spring:
  profiles: test
  application:
    name: SPRING-CLOUD-INVENTORY-7002-TEST
  #Spring boot 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_02
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.199.14:7001/eureka/
  instance:
    instance-id: spring-cloud-inventory    #服务实例名称修改
    prefer-ip-address: true   #访问路径显示Ip
#MyBatis配置
#mybatis:
#  type-aliases-package: com.gsau.Inventory.projo
mybatis:
  mapper-locations: classpath:/myBatisConfig/mappers/*.xml
#TxManager配置
tm:
  manager:
    url: http://192.168.199.14:8888/tx/manager/
---
server:
  port: 7002

spring:
  profiles: deploy
  application:
    name: SPRING-CLOUD-INVENTORY-7002-TEST
  #Spring boot 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_02
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.199.14:7001/eureka/
  instance:
    instance-id: spring-cloud-inventory    #服务实例名称修改
    prefer-ip-address: true   #访问路径显示Ip
#MyBatis配置
#mybatis:
#  type-aliases-package: com.gsau.Inventory.projo
mybatis:
  mapper-locations: classpath:/myBatisConfig/mappers/*.xml
#TxManager配置
tm:
  manager:
    url: http://192.168.199.14:8888/tx/manager/