spring:
  profiles:
    active: dev                                   #当前应用的环境是开发环境
---
server:
  port: 7003

spring:
  profiles: dev
  application:
    name: SPRING-CLOUD-ORDER-7003-DEV
  thymeleaf:                                  #spring boot thymeleaf配置
  #在spring-boot下，默认约定了Controller试图跳转中thymeleaf模板文件的的前缀prefix是”classpath:/templates/”,后缀suffix是”.html”
  #这个在application.properties配置文件中是可以修改的。
  #thymeleaf对html的标签约束非常严格，所有的标签必须有开有闭，比如<br></br>或者<br/>是可以的，但是<br>会报错，
  # 配置spring.thymeleaf.mode=LEGACYHTML5 目的就是为了解决这个问题，可以使页面松校验。
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#Spring boot 数据源配置    
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_01
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    schema: classpath:sql/Dump20170725.sql
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://ureka-server-host:7001/eureka/
    registerWithEureka: true
    fetch-registry: true
  instance:
    instance-id: spring-cloud-order       #服务实例名称修改
    prefer-ip-address: true               #访问路径显示Ip
#mybatis配置
mybatis:
  mapper-locations: classpath:/myBatisConfig/mappers/*.xml
#Tx-Manager配置
tm:
  manager:
    url:  http://tx-manager-host:8888/tx/manager/
---
server:
  port: 7003

spring:
  profiles: test
  application:
    name: SPRING-CLOUD-ORDER-7003-TEST
  thymeleaf:                                  #spring boot thymeleaf配置
  #在spring-boot下，默认约定了Controller试图跳转中thymeleaf模板文件的的前缀prefix是”classpath:/templates/”,后缀suffix是”.html”
  #这个在application.properties配置文件中是可以修改的。
  #thymeleaf对html的标签约束非常严格，所有的标签必须有开有闭，比如<br></br>或者<br/>是可以的，但是<br>会报错，
  # 配置spring.thymeleaf.mode=LEGACYHTML5 目的就是为了解决这个问题，可以使页面松校验。
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  #Spring boot 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_01
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://ureka-server-host:7001/eureka/
    registerWithEureka: true
    fetch-registry: true
  instance:
    instance-id: spring-cloud-order       #服务实例名称修改
    prefer-ip-address: true               #访问路径显示Ip
#mybatis配置
mybatis:
  mapper-locations: classpath:/myBatisConfig/mappers/*.xml
#Tx-Manager配置
# tm:
#   manager:
#       url:  http://tx-manager-host:8888/tx/manager/
---
server:
  port: 7003

spring:
  profiles: deploy
  application:
    name: SPRING-CLOUD-ORDER-7003-DEPLOY
  thymeleaf:                                  #spring boot thymeleaf配置
  #在spring-boot下，默认约定了Controller试图跳转中thymeleaf模板文件的的前缀prefix是”classpath:/templates/”,后缀suffix是”.html”
  #这个在application.properties配置文件中是可以修改的。
  #thymeleaf对html的标签约束非常严格，所有的标签必须有开有闭，比如<br></br>或者<br/>是可以的，但是<br>会报错，
  # 配置spring.thymeleaf.mode=LEGACYHTML5 目的就是为了解决这个问题，可以使页面松校验。
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  #Spring boot 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_01
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://ureka-server-host:7001/eureka/
    registerWithEureka: true
    fetch-registry: true
  instance:
    instance-id: spring-cloud-order       #服务实例名称修改
    prefer-ip-address: true               #访问路径显示Ip
#mybatis配置
mybatis:
  mapper-locations: classpath:/myBatisConfig/mappers/*.xml
#Tx-Manager配置
tm:
  manager:
    url:  http://tx-manager-host:8888/tx/manager/
