spring:
  profiles:
    active: dev                                   #当前应用的环境是开发环境
---
server:
  port: 8001

spring:
  profiles: dev                                   #开发环境的配置
  application:
    name: SPRINGCLOUD-SESSION-ZUUL-8001-DEV
  redis:
    host: redis-host
    port: 6379
    #    password: 123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://ureka-server-host:7001/eureka/
  instance:
    instance-id: springcloud-session-zuul
    prefer-ip-address: true   #访问路径显示Ip

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#网关配置
zuul:
  routes:
    inventory-service:                             #自定义名称（inventory-service）表示代理inventory微服务
      path: /inventory/**                          #/inventory/开头的路径转发至表示代理inventory微服务
      serviceId: SPRING-CLOUD-INVENTORY-7002-DEV
      sensitiveHeaders: "*"                        #解决经过网关zuul转发请求后发生session失效
    order-service:
      path: /order/**
      serviceId: SPRING-CLOUD-ORDER-7003-DEV
      sensitiveHeaders: "*"
    portal-service:
      path: /portal/**
      serviceId: SPRING-CLOUD-PORTAL-7004-DEV
      sensitiveHeaders: "*"
    tx-service:
      path: /tx-manager/**
      serviceId: TX-MANAGER
      sensitiveHeaders: "*"
  ignored-services: "*"
  prefix: /integrate
---
server:
  port: 8001

spring:
  profiles: test                                   #开发环境的配置
  application:
    name: SPRINGCLOUD-SESSION-ZUUL-8001-TEST
  redis:
    host: redis-host
    port: 6379
    #    password: 123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://ureka-server-host:7001/eureka/
  instance:
    instance-id: springcloud-session-zuul
    prefer-ip-address: true   #访问路径显示Ip

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#网关配置
zuul:
  routes:
    inventory-service:                             #自定义名称（inventory-service）表示代理inventory微服务
      path: /inventory/**                          #/inventory/开头的路径转发至表示代理inventory微服务
      serviceId: spring-cloud-inventory
      sensitiveHeaders: "*"                        #解决经过网关zuul转发请求后发生session失效
    order-service:
      path: /order/**
      serviceId: spring-cloud-order
      sensitiveHeaders: "*"
    portal-service:
      path: /portal/**
      serviceId: spring-cloud-portal
      sensitiveHeaders: "*"
  ignored-services: "*"
  prefix: /test
---
server:
  port: 8001

spring:
  profiles: DEPLOY                                   #开发环境的配置
  application:
    name: SPRINGCLOUD-SESSION-ZUUL-8001-DEPLOY
  redis:
    host: redis-host
    port: 6379
    #    password: 123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://ureka-server-host:7001/eureka/
  instance:
    instance-id: springcloud-session-zuul
    prefer-ip-address: true   #访问路径显示Ip

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
#网关配置
zuul:
  routes:
    inventory-service:                             #自定义名称（inventory-service）表示代理inventory微服务
      path: /inventory/**                          #/inventory/开头的路径转发至表示代理inventory微服务
      serviceId: spring-cloud-inventory
      sensitiveHeaders: "*"                        #解决经过网关zuul转发请求后发生session失效
    order-service:
      path: /order/**
      serviceId: spring-cloud-order
      sensitiveHeaders: "*"
    portal-service:
      path: /portal/**
      serviceId: spring-cloud-portal
      sensitiveHeaders: "*"
  ignored-services: "*"
  prefix: /test
